[window]
opacity = 0.85
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true
# option_as_alt = "RightOnly" # MacOS only

[font]
size = 12.0

[font.normal]
family = "SauceCodePro Nerd Font"

[shell]
program = "/bin/zsh"
