import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.85
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true
# option_as_alt = "RightOnly" # MacOS only

[font]
size = 12.0

[font.normal]
family = "SauceCodePro Nerd Font"

[shell]
program = "/bin/zsh"

[env]
TERM = "xterm-256color"

